### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [raghavagg01/Qsol#12]
Hai,
I would love to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal.  It would look like the photo mentioned below.
![Template](https://user-images.githubusercontent.com/64524822/104024244-d7d11b00-51e8-11eb-91ec-995223a8449e.png)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by avidraghav** [comment]
I'll be glad if u can suggest some improvements to the app also: https://play.google.com/store/apps/details?id=com.application.kurukshetrauniversitypapers
Any suggestions will help, software contribution is not necessary :)

**Comment by muthuannamalai12** [comment]
> I'll be glad if u can suggest some improvements to the app also: https://play.google.com/store/apps/details?id=com.application.kurukshetrauniversitypapers
> Any suggestions will help, software contribution is not necessary :)

Sure I would  do it

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly Review it
