### ISSUE TITLE
Integrate Welcome  Bot

### ISSUE THREAD

**Issue by akrish4** [raghavagg01/Qsol#13]
Hi @raghavagg01 

I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
Kindly do assign me this issue 
( config file having a proper message)

For reference, kindly check out: https://github.com/apps/welcome

**Comment by avidraghav** [comment]
Go ahead.

**Comment by akrish4** [comment]
#15 PR

**Comment by akrish4** [comment]
@raghavagg01 kindly pls add the same labels to pr also
otherwise it won't be counted as my contribution towards dwoc as DWOC count if and only if issue and pr both have same labels
so kindly do add th same labels here also DWOC and Level-1 label
